language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
install: composer install
script: composer phpunit
after_script:
  - composer phpcs
  - composer phploc
  - composer phpcpd
  - composer phpmd
